---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oura
data:
  daemon.toml: |-
    [source]
    type = "N2N"
    address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
    magic = "mainnet"
    since = [51059593, "6ceffc63e6d7118e82ab3387b608d27d7e89f6524f81494fd182208cf2b4da40"]

    [[filters]]
    type = "Fingerprint"

    [[filters]]
    type = "Selection"

    [filters.check]
    predicate = "variant_in"
    argument = ["CIP25Asset"]

    [sink]
    type = "Elastic"
    url = "https://sink-es-http:9200"
    index = "oura.sink.cip25assets"
    idempotency = true

    [sink.credentials]
    type = "Basic"
    username = "elastic"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oura
  labels:
    app: oura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oura
  template:
    metadata:
      labels:
        app: oura
    spec:
      containers:
      - name: main
        image: ghcr.io/txpipe/oura:v1.0.1
        env:
          - name: "RUST_LOG"
            value: "info"
          - name: "OURA_SINK_CREDENTIALS_PASSWORD"
            valueFrom:
              secretKeyRef:
                key: elastic
                name: sink-es-elastic-user 
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 500Mi
            cpu: 200m
        args:
          - "daemon"
        volumeMounts:
          - mountPath: /etc/oura
            name: oura-config
      volumes:
      - name: oura-config
        configMap:
          name: oura
